module Elastic_Band

use types_m
use ansi_colors
use Read_Parms
use util_m       , only: split_line
use EDT_util_m   , only: parse_this, bring_to_GCenter 
use DWFF_stuff   , only: configuration_energy
use Build_DWFF   , only: include_DWFF_parameters , HOH_diss_parms

public :: Build_Configurations , Pick_Configurations

private

contains
!
!
!
!====================================================
 subroutine Build_Configurations( sys, pes_scan_flag)
!====================================================
implicit none 
type(universe)            , intent(inout) :: sys
character(len=*), optional, intent(in)    :: pes_scan_flag

! local variables ...
integer                        :: i, n, n_steps, pes 
real*8                         :: versor(3)
real*8                         :: displacement, step
real*8           , allocatable :: config_erg(:)
logical                        :: pes_scan = .false.
character(len=96)              :: string
type(universe)   , allocatable :: trj(:)


if(present(pes_scan_flag) .and. (pes_scan_flag=="y")) pes_scan=.true.

call user_interface( sys, n_steps, step, versor , pes_scan)  

! generate configurations ...
allocate( trj(0:n_steps) )

if(pes_scan) then
    allocate( config_erg(0:n_steps) )
    OPEN(file='pes_erg.dat', status='unknown', action='write', newunit=pes)
end if

! bring system to the center
call bring_to_GCenter(sys%atom)

do n = 0, n_steps

    displacement = n * step  
    trj(n) = sys
    
    write(string,'(A55,F7.4)') "reaction path generated by DynEMol, this bond displacement = ", displacement
 
    trj(n)% System_Characteristics = string

    do concurrent ( i=1:sys%N_of_atoms , sys%atom(i)%translate ) 
            trj(n)%atom(i)%xyz = sys%atom(i)%xyz + versor * displacement
    end do
 
    if(pes_scan) then
        config_erg(n) = configuration_energy(trj(n)%atom)
        write(pes,'(2f10.4)') displacement, config_erg(n)
    end if

end do

call Save_PDB_Trajectories(trj) 

end subroutine Build_Configurations
!
!
!
!=======================================================
subroutine user_interface( sys, n_steps, step, versor, pes_scan)
!=======================================================
implicit none 
type(universe), intent(inout):: sys
integer       , intent(out)  :: n_steps 
real*8        , intent(out)  :: step
real*8        , intent(out)  :: versor(3)
logical       , intent(in)   :: pes_scan

! local variables ...
real*8 :: path_length

CALL system( "clear" )

! ------------------------------------------------------------
! Read frame indices
! ------------------------------------------------------------
write(*,'(/a)') bold//blue// &
    ">>> Creating frames from a single structure <<<"//reset

write(*,'(/a)') green//"Purpose:"//reset
write(*,'(/a)') "  Generate a set of configurations by moving a selected atomic fragment along a prescribed path."

write(*,'(/a)') green//"Required steps:"//reset
write(*,'(/a)') "  1) Define the atomic fragment that will move (a single atom or a group of atoms)."
write(*,'(/a)') "  2) Define the path length (minimum and maximum distance, in consistent units)."
write(*,'(/a)') "  3) Specify the number of configurations to be generated."
write(*,'(/a)') "  4) Define the direction of the motion (typically a bond vector or user-defined axis)."

write(*,'(/a)') green//"Notes:"//reset
write(*,'(/a)') bold//"  - The fragment must be placed at the initial position before starting this routine."//reset
write(*,'(/a)')       "  - All generated frames preserve the original system topology."
write(*,'(/a)')       "  - This procedure is typically used to scan bond stretching,"
write(*,'(/a)')       "    adsorption paths, or constrained reaction coordinates."

! ------------------------------------------------------------ 
! Input data
! ------------------------------------------------------------
write(*,'(/a)') bold//green//"Step 1: define fragment that will move."//reset

call selecting( sys, instance=1, message=' Choose keyword of stuff to TRANSLATE : ')

write(*,'(/a)') bold//cyan//"Steps 2,3,4: define reaction path (origin = current position)."//reset

write(*,'(/a)') green//"> Length of the reaction path "//yellow//"(Angs. units):"//reset
write(*,'(a)',advance='no') yellow//">>> "//reset
read (*,*) path_length
write(*,'(/a)') green//"> Enter the number of steps:"//reset
write(*,'(a)',advance='no') yellow//">>> "//reset
read (*,*) n_steps

step = path_length / real(n_steps, kind=8)

versor = translation_direction(sys)                                                                                                                                    
if(pes_scan) then
    call selecting( sys, instance=2, message=' Identify atoms that contribute to the PES calculation: ') 
    call include_DWFF_parameters 
end if

end subroutine user_interface
!
!
!
!=============================================
subroutine selecting( sys, instance, message )
!=============================================
implicit none 
type(universe)  , intent(inout) :: sys
integer         , intent(in)    :: instance
character(len=*), intent(in)    :: message

! local variables ...
integer                        :: i
integer          , allocatable :: nr(:) , indx(:)
character(len=1)               :: choice
character(len=3) , allocatable :: residue(:)
character(len=80)              :: line
logical          , allocatable :: mask(:)

! reset varible ...
select case(instance)
   case(1) 
   sys% atom(:)% translate = .false.
   case(2) 
   sys% atom(:)% DWFF = .false.
end select

CALL systemQQ( "clear" )

write(*,'(/a)') bold // orange // message // reset

write(*,'(a)') bold // cyan // ' (1) = tuning already done' // reset
write(*,'(a)') bold // cyan // ' (2) = residue number ' // reset
write(*,'(a)') bold // cyan // ' (3) = residue name ' // reset
write(*,'(a)') bold // cyan // ' (4) = atom index ' // reset

write(*,'(/a)', advance='no') bold // yellow // '>>>   ' // reset
read (*,'(a)') choice

associate( atom => sys% atom)

    allocate( mask(size(atom)) )
    
    select case( choice )
    
        case( '1' )
            ! do nothing, proceed ...
    
        case( '2' )
            write(*,'(/a)', advance='no') green // &
            "enter the residue numbers to be changed: separated by spaces, or in the format 'first:last' (press ENTER to send) : " // reset
            read (*,'(a)') line
    
            nr = parse_this(line)
            do i = 1 , size(nr)
    
                mask = (atom% nresid == nr(i))
    
                select case (instance)
                case (1)
                    where(mask) atom(:)% translate = .true.
                case (2)
                    where(mask) atom(:)% DWFF = .true.
                end select
            end do
    
        case( '3' )
            write(*,'(/a)', advance='no') green // &
            "enter the residue names to be changed, separated by spaces (press ENTER to send) : " // reset
            read (*,'(a)') line
    
            residue = split_line(line)
            do i = 1 , size(residue)
    
                mask = (atom% resid == residue(i))
    
                select case (instance)
                case (1)
                    where(mask) atom(:)% translate = .true.
                case (2)
                    where(mask) atom(:)% DWFF = .true.
                end select
            end do
    
        case( '4' )
            write(*,'(/a)') green // "enter the indices of the atoms to be changed," // reset
            write(*,'(a)', advance='no') green // "separated by spaces, or in the format 'first:last' (press ENTER to send) : " // reset
            read (*,'(a)') line
    
            indx = parse_this(line)
            print*, indx
            select case( instance )
                   case(1)
                       atom(indx)% translate = .true.
                   case(2)
                       atom(indx)% DWFF = .true.
            end select
    
    end select
end associate

deallocate(mask)

end subroutine selecting
!
!
!
!========================================================
function translation_direction( system ) result( versor )
!========================================================
    implicit none 
    type(universe), intent(inout) :: system
    
    ! local variables ...
    integer :: option, at1, at2, at3
    real*8  :: T_vector(3), versor(3)
    
    ! define translation vector
    write(*,'(/a)') bold//orange//"define translation vector."//reset
    write(*,'(/a)') yellow//"> Use: (1)-cartesian axis , (2)-ad-hoc vector ,  (3)-normal vector? "//reset
    write(*,'(a)',advance='no') yellow//">>> "//reset
    read(*,*) option
    
    select case (option)
    
       case(1)
            ! use cartesian vectors 
            write(*,'(/a)') '> enter translation vector (T_x,T_y,T_z) as a Real number:'
            write(*,'(a)',advance='no') 'T_x = '
            read (*,*) T_vector(1)
            write(*,'(a)',advance='no') 'T_y = '
            read (*,*) T_vector(2)
            write(*,'(a)',advance='no') 'T_z = '
            read (*,*) T_vector(3)
            versor = T_vector / sqrt( dot_product(T_vector,T_vector) )
    
       case(2) 
            ! define translation vector 
            write(*,'(/a)') '> define vector: at1 ======> at2'
            write(*,'(a)',advance='no') 'index of atom 1 = '
            read(*,*) at1
            write(*,'(a)',advance='no') 'index of atom 2 = '
            read(*,*) at2
    
            versor = (system% atom(at2)% xyz - system% atom(at1)% xyz) / sqrt(sum( (system% atom(at2)% xyz-system% atom(at1)% xyz)**2) )
    
       case(3) 
            ! define rotation vector 
            write(*,'(/a)') '> define vector perpendicular to the plane: '
            write(*,'(/a)') '            at1    at3                      '
            write(*,'(a)')  '              \    /                        '
            write(*,'(a)')  '               \  /                         '
            write(*,'(a)')  '                \/                          '
            write(*,'(a)')  '                at2                         '
            write(*,'(/a)',advance='no') 'index of atom 1 = '
            read(*,*) at1
            write(*,'(a)',advance='no') 'index of atom 2 = '
            read(*,*) at2
            write(*,'(a)',advance='no') 'index of atom 3 = '
            read(*,*) at3
    
            ! the versor ...
            versor = vector_product(system,at1,at2,at3)
    
    end select

    print*,"" 

end function translation_direction
!
!
!
!======================================================
 function vector_product(sys,at1,at2,at3) result(w_vec)
!======================================================
    implicit none
    type(universe) , intent(in) :: sys
    integer        , intent(in) :: at1
    integer        , intent(in) :: at2
    integer        , intent(in) :: at3
    
    !local variables ...
    real*8 :: u_vec(3) , v_vec(3) , w_vec(3) 
    
    u_vec = (sys% atom(at1)% xyz - sys% atom(at2)% xyz) 
    v_vec = (sys% atom(at3)% xyz - sys% atom(at2)% xyz) 
    
    w_vec(1) = u_vec(3)*v_vec(2) - u_vec(2)*v_vec(3)
    w_vec(2) = u_vec(1)*v_vec(3) - u_vec(3)*v_vec(1)
    w_vec(3) = u_vec(2)*v_vec(1) - u_vec(1)*v_vec(2)
    
    w_vec = w_vec / sqrt( dot_product(w_vec,w_vec) )

end function vector_product
!
!
!
!================================================
 subroutine Save_PDB_Trajectories(trj, file_name)
!================================================
type(universe), allocatable, intent(inout) :: trj(:)
character(*)  , optional   , intent(in)    :: file_name

! local variables ...
integer      :: i, j, k, last_config
character(1) :: YorN

If( present(file_name) ) then
    OPEN(unit = 4, file = file_name          , status = 'unknown', action = 'write')
else 
    OPEN(unit = 4, file = 'frames-output.pdb', status = 'unknown', action = 'write')
end if

last_config = size(trj) -1

do j = 0 , last_config

    write(4,5) 'REMARK' , trj(j)% System_Characteristics
    write(4,1) 'CRYST1' , trj(j)%box(1) , trj(j)%box(2) , trj(j)%box(3) , 90.0 , 90.0 , 90.0 , 'P 1' , '1'
    write(4,3) 'MODEL'  , j

    ! where MMSymbol is not defined MMSymbol = symbol ...
    where( trj(j)%atom%MMSymbol == "XXX" ) trj(j)%atom%MMSymbol = trj(j)%atom%symbol

    do i = 1 , trj(j)%N_of_atoms

            write(4,2)  'ATOM  '                            ,  &    ! <== non-standard atom
                        i                                   ,  &    ! <== global number
                        trj(j)%atom(i)%MMSymbol             ,  &    ! <== atom type
                        ' '                                 ,  &    ! <== alternate location indicator
                        trj(j)%atom(i)%resid                ,  &    ! <== residue name
                        ' '                                 ,  &    ! <== chain identifier
                        trj(j)%atom(i)%nresid               ,  &    ! <== residue sequence number
                        ' '                                 ,  &    ! <== code for insertion of residues
                        ( trj(j)%atom(i)%xyz(k) , k=1,3 )   ,  &    ! <== xyz coordinates 
                        1.00                                ,  &    ! <== occupancy
                        0.00                                ,  &    ! <== temperature factor
                        ' '                                 ,  &    ! <== segment identifier
                        ' '                                 ,  &    ! <== here only for tabulation purposes
                        trj(j)%atom(i)%symbol               ,  &    ! <== chemical element symbol
                        trj(j)%atom(i)%charge                       ! <== charge on the atom
    end do

    write(4,'(a)') 'MASTER'
    write(4,'(a)') 'END'

end do

close(4)

1 FORMAT(a6,3F9.3,3F7.2,a11,a4)
2 FORMAT(a6,i5,a5,a1,a3,a2,i4,a4,3F8.3,2F6.2,a4,a6,a2,F8.4)              
3 FORMAT(a5,i8)
4 FORMAT(a6,t15,a21)
5 FORMAT(a6,t10,a72)

write(*,'(/a)') ' >>> frames-output.pdb : writing done, press any key <<<'
write(*,'(/a)') "That's all ? (y/n)"
read (*,'(a)') YorN
if( YorN /= "n" ) stop

end subroutine Save_PDB_Trajectories
!
!
!
!============================================
subroutine Pick_Configurations( trj , f_type)
!============================================
    implicit none
    type(universe)  , allocatable   , intent(inout) :: trj(:)
    integer                         , intent(in)    :: f_type

    character(4) :: file_format(2)=["vasp","pdb"] 
   
    trj = trj  
    select case( file_format(f_type) )
       case( "vasp" )
          print*, bold//red//"to be implemented if required:"//reset
       case( "pdb" ) 
          print*, bold//red//"to be implemented if required:"//reset
    end select

end subroutine Pick_Configurations
!
!
!
end module Elastic_Band
